"""org level 3

Revision ID: 590b89834b79
Revises: 507dfc471eeb
Create Date: 2023-07-12 15:40:07.793329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590b89834b79'
down_revision = '507dfc471eeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations_level_3',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('level1_id', sa.Integer(), nullable=True),
    sa.Column('level_name', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('audit_sheet_creation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level1_id'], ['md_wqms_mock.organizations_level2.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['md_wqms_mock.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_organizations_level_3_id'), 'organizations_level_3', ['id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_organizations_level_3_level1_id'), 'organizations_level_3', ['level1_id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_organizations_level_3_organization_id'), 'organizations_level_3', ['organization_id'], unique=False, schema='md_wqms_mock')
    op.add_column('organizations_level2', sa.Column('audit_sheet_creation', sa.Boolean(), nullable=True))
    op.drop_constraint('organizations_level2_ibfk_1', 'organizations_level2', type_='foreignkey')
    op.drop_constraint('organizations_level2_ibfk_2', 'organizations_level2', type_='foreignkey')
    op.create_foreign_key(None, 'organizations_level2', 'organizations', ['organization_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.create_foreign_key(None, 'organizations_level2', 'organizations', ['level1_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.drop_constraint('permissions_ibfk_1', 'permissions', type_='foreignkey')
    op.create_foreign_key(None, 'permissions', 'roles', ['role_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.drop_constraint('roles_ibfk_1', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'organizations', ['organization_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('roles_ibfk_1', 'roles', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'permissions', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('permissions_ibfk_1', 'permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'organizations_level2', schema='md_wqms_mock', type_='foreignkey')
    op.drop_constraint(None, 'organizations_level2', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('organizations_level2_ibfk_2', 'organizations_level2', 'organizations', ['level1_id'], ['id'])
    op.create_foreign_key('organizations_level2_ibfk_1', 'organizations_level2', 'organizations', ['organization_id'], ['id'])
    op.drop_column('organizations_level2', 'audit_sheet_creation')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_level_3_organization_id'), table_name='organizations_level_3', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_level_3_level1_id'), table_name='organizations_level_3', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_level_3_id'), table_name='organizations_level_3', schema='md_wqms_mock')
    op.drop_table('organizations_level_3', schema='md_wqms_mock')
    # ### end Alembic commands ###
