"""created first migration

Revision ID: 78bb6c7ea26c
Revises: 
Create Date: 2023-07-06 19:54:47.945501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bb6c7ea26c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.String(length=250), nullable=True),
    sa.Column('organization_pic', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_organizations_id'), 'organizations', ['id'], unique=False, schema='md_wqms_mock')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_users_email_id'), 'users', ['email_id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_users_id'), 'users', ['id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_users_password'), 'users', ['password'], unique=False, schema='md_wqms_mock')
    op.create_table('organizations_level2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level1_id', sa.Integer(), nullable=True),
    sa.Column('level_name', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level1_id'], ['md_wqms_mock.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_organizations_level2_id'), 'organizations_level2', ['id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_organizations_level2_level1_id'), 'organizations_level2', ['level1_id'], unique=False, schema='md_wqms_mock')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=250), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['md_wqms_mock.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_roles_id'), 'roles', ['id'], unique=False, schema='md_wqms_mock')
    op.create_index(op.f('ix_md_wqms_mock_roles_organization_id'), 'roles', ['organization_id'], unique=False, schema='md_wqms_mock')
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=250), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['md_wqms_mock.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='md_wqms_mock'
    )
    op.create_index(op.f('ix_md_wqms_mock_permissions_id'), 'permissions', ['id'], unique=False, schema='md_wqms_mock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md_wqms_mock_permissions_id'), table_name='permissions', schema='md_wqms_mock')
    op.drop_table('permissions', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_roles_organization_id'), table_name='roles', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_roles_id'), table_name='roles', schema='md_wqms_mock')
    op.drop_table('roles', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_level2_level1_id'), table_name='organizations_level2', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_level2_id'), table_name='organizations_level2', schema='md_wqms_mock')
    op.drop_table('organizations_level2', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_users_password'), table_name='users', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_users_id'), table_name='users', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_users_email_id'), table_name='users', schema='md_wqms_mock')
    op.drop_table('users', schema='md_wqms_mock')
    op.drop_index(op.f('ix_md_wqms_mock_organizations_id'), table_name='organizations', schema='md_wqms_mock')
    op.drop_table('organizations', schema='md_wqms_mock')
    # ### end Alembic commands ###
