"""org level 3 sec

Revision ID: 9053a96d290e
Revises: c2c2798a08b1
Create Date: 2023-07-13 12:31:56.812056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9053a96d290e'
down_revision = 'c2c2798a08b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organizations_level2_ibfk_1', 'organizations_level2', type_='foreignkey')
    op.drop_constraint('organizations_level2_ibfk_2', 'organizations_level2', type_='foreignkey')
    op.create_foreign_key(None, 'organizations_level2', 'organizations', ['level1_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.create_foreign_key(None, 'organizations_level2', 'organizations', ['organization_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.drop_constraint('organizations_level_3_ibfk_2', 'organizations_level_3', type_='foreignkey')
    op.drop_constraint('organizations_level_3_ibfk_1', 'organizations_level_3', type_='foreignkey')
    op.create_foreign_key(None, 'organizations_level_3', 'organizations', ['organization_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.create_foreign_key(None, 'organizations_level_3', 'organizations_level2', ['level2_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.drop_constraint('permissions_ibfk_1', 'permissions', type_='foreignkey')
    op.create_foreign_key(None, 'permissions', 'roles', ['role_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    op.drop_constraint('roles_ibfk_1', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'organizations', ['organization_id'], ['id'], source_schema='md_wqms_mock', referent_schema='md_wqms_mock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('roles_ibfk_1', 'roles', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'permissions', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('permissions_ibfk_1', 'permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'organizations_level_3', schema='md_wqms_mock', type_='foreignkey')
    op.drop_constraint(None, 'organizations_level_3', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('organizations_level_3_ibfk_1', 'organizations_level_3', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('organizations_level_3_ibfk_2', 'organizations_level_3', 'organizations_level2', ['level2_id'], ['id'])
    op.drop_constraint(None, 'organizations_level2', schema='md_wqms_mock', type_='foreignkey')
    op.drop_constraint(None, 'organizations_level2', schema='md_wqms_mock', type_='foreignkey')
    op.create_foreign_key('organizations_level2_ibfk_2', 'organizations_level2', 'organizations', ['level1_id'], ['id'])
    op.create_foreign_key('organizations_level2_ibfk_1', 'organizations_level2', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
